### PR TITLE
Escape <> in rulername

### PR DESCRIPTION
**Pull request by vhffm**
Since apparently <> are valid chars in the rulername [1], I escaped them. Hope I've done this right [2].

Hit me on IRC (morrow) if something's fishy or this is crap.

[1] See, for example, galaxy 4:3 ~ http://pascans.zapto.org/4.3/
[2] Fixed ~ http://ultores.cheleb.net/4.3/

### CODE REVIEW

**Comment by ellonweb** [comment]
This looks good, thanks. If you have time could you look at maybe a similar commit for planetname, galaxyname and maybe anything else you think relevant? (Things like intel nick don't need this as a alphanumeric limit is already in place).

On a separate note I had a look at your host and your graph cache isn't being cleared. Can you check you have this commit: https://github.com/ellonweb/merlin/commit/1c665326a304ac15e92d0ec66d6f8f5c542949e4 and also if you're running on a POSIX machine that you've +777'd /merlin/Arthur/graphs/. If that doesn't rectify the problem please raise another ticket and I'll try and find some time to get online and investigate!

**Comment by vhffm** [comment]
I tried signing up with a fishy (with <>) planet name, and PA complained. When I have some time I can prod some people to try out these chars in alliance and galaxy names and other stuff I can think of.

Thanks for the hint with the cache; I'll look into it.

**Comment by vhffm** [comment]
Argh ... hit the wrong button. Close at your own discretion :).

**Comment by vhffm** [comment]
Wow ... I think github or me choked on something. I'm closing this thing ... just pull whenever.

**Pull request merged**
